/* eslint-disable no-control-regex */
// Hàm này dùng để loại bỏ dấu trong tiếng Việt hoặc các ký tự Latin mở rộng của các quốc gia khác nhưng không phải tất cả.
// Sau này sẽ thiết lập để nó hoạt động tốt cho nhiều loại ký tự Latin hơn nếu cần thiết

const regexpDiacritics = /[\u0300-\u036f]/g;
const regexpSpecialCharacters = /[^\u0000-\u007E]/g;

const diacriticsMap = {
  Ā: "A",
  ā: "a",
  Ă: "A",
  ă: "a",
  Ą: "A",
  ą: "a",
  Ć: "C",
  ć: "c",
  Ĉ: "C",
  ĉ: "c",
  Ċ: "C",
  ċ: "c",
  Č: "C",
  č: "c",
  Ď: "D",
  ď: "d",
  Đ: "D",
  đ: "d",
  Ē: "E",
  ē: "e",
  Ĕ: "E",
  ĕ: "e",
  Ė: "E",
  ė: "e",
  Ę: "E",
  ę: "e",
  Ě: "E",
  ě: "e",
  Ĝ: "G",
  ĝ: "g",
  Ğ: "G",
  ğ: "g",
  Ġ: "G",
  ġ: "g",
  Ģ: "G",
  ģ: "g",
  Ĥ: "H",
  ĥ: "h",
  Ħ: "H",
  ħ: "h",
  Ĩ: "I",
  ĩ: "i",
  Ī: "I",
  ī: "i",
  Ĭ: "I",
  ĭ: "i",
  Į: "I",
  į: "i",
  İ: "I",
  ı: "i",
  Ĳ: "IJ",
  ĳ: "ij",
  Ĵ: "J",
  ĵ: "j",
  Ķ: "K",
  ķ: "k",
  ĸ: "k",
  Ĺ: "L",
  ĺ: "l",
  Ļ: "L",
  ļ: "l",
  Ľ: "L",
  ľ: "l",
  Ŀ: "L",
  ŀ: "l",
  Ł: "L",
  ł: "l",
  Ń: "N",
  ń: "n",
  Ņ: "N",
  ņ: "n",
  Ň: "N",
  ň: "n",
  ŉ: "n",
  Ŋ: "N",
  ŋ: "n",
  Ō: "O",
  ō: "o",
  Ŏ: "O",
  ŏ: "o",
  Ő: "O",
  ő: "o",
  Œ: "OE",
  œ: "oe",
  Ŕ: "R",
  ŕ: "r",
  Ŗ: "R",
  ŗ: "r",
  Ř: "R",
  ř: "r",
  Ś: "S",
  ś: "s",
  Ŝ: "S",
  ŝ: "s",
  Ş: "S",
  ş: "s",
  Š: "S",
  š: "s",
  Ţ: "T",
  ţ: "t",
  Ť: "T",
  ť: "t",
  Ŧ: "T",
  ŧ: "t",
  Ũ: "U",
  ũ: "u",
  Ū: "U",
  ū: "u",
  Ŭ: "U",
  ŭ: "u",
  Ů: "U",
  ů: "u",
  Ű: "U",
  ű: "u",
  Ų: "U",
  ų: "u",
  Ŵ: "W",
  ŵ: "w",
  Ŷ: "Y",
  ŷ: "y",
  Ÿ: "Y",
  Ź: "Z",
  ź: "z",
  Ż: "Z",
  ż: "z",
  Ž: "Z",
  ž: "z",
  ſ: "s",

  // Các ký tự đặc biệt khác
  Æ: "AE",
  æ: "ae",
  Þ: "TH",
  þ: "th",
  ß: "ss",
  Ð: "D",
  ð: "d",
  Ø: "O",
  ø: "o",
};

/**
 * Loại bỏ dấu trong tiếng Việt và chuyển đổi các ký tự Latin mở rộng sang ASCII
 * @param text - Chuỗi cần loại bỏ dấu
 * @returns Chuỗi đã loại bỏ dấu
 * @example
 * removeDiacritics("Tiếng Việt") // "Tieng Viet"
 * removeDiacritics("Đặng Văn Lâm") // "Dang Van Lam"
 */
const removeDiacritics = (text: string): string => {
  return text
    .normalize("NFD")
    .replace(regexpDiacritics, "") // Loại bỏ dấu phụ
    .replace(
      regexpSpecialCharacters,
      (char) => diacriticsMap[char as keyof typeof diacriticsMap] || char
    ) // Việc chỉ loại bỏ dấu trong tiếng Việt sẽ không hoạt động với các ký tự Latin mở rộng khác nên phải dùng thêm dòng code này
    .normalize("NFC");
};

export default removeDiacritics;
